require: rubocop-rspec
inherit_from: .rubocop_todo.yml

Metrics/ModuleLength:
  Exclude:
  - 'spec/**/*'
  - 'test/**/*'

Metrics/MethodLength:
  Max: 12

Metrics/AbcSize:
  Exclude:
  - 'lib/occi/core/parsers/text/*'
  - 'lib/occi/core/parsers/json/*'
  - 'lib/occi/core/helpers/parser_dereferencer.rb'
  - 'lib/occi/core/helpers/instance_attribute_resetter.rb'

Metrics/LineLength:
  Max: 120
  Exclude:
  - 'lib/occi/core/parsers/text/constants.rb'

Metrics/BlockLength:
  Exclude:
  - 'spec/**/*'
  - 'test/**/*'
  - '*.gemspec'

ClassLength:
  Max: 180

Style/Documentation:
  Exclude:
  - 'spec/**/*'
  - 'test/**/*'
  - 'lib/occi/core/version.rb'

Style/StructInheritance:
  Exclude:
  - 'lib/occi/core/attribute.rb'

Style/NilComparison:
  Exclude:
  - 'spec/occi/core/category_spec.rb'

Style/FileName:
  Exclude:
  - 'lib/occi/infrastructure-ext.rb'

Style/YodaCondition:
  Exclude:
  - 'lib/occi/core/helpers/parser_dereferencer.rb'

RSpec/MultipleExpectations:
  Max: 5

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/SubjectStub:
  Exclude:
    - 'spec/**/*'

RSpec/MessageExpectation:
  Exclude:
    - 'spec/**/*'
